### ALL Conditions:

1-shape: (2 3 4 or 6 items) - just delayed forgetting / equal probe probs

Attention conditions - precues with

100%, 80/20, 50% X 4 item or 6 item (with probe probs being enhanced for some of them)

### For all of these, you can just run for a ton of Time-Steps to remove the TS-per-sec parameters -- just get number of time-steps...






In [27]:
# part 1:
# simulate the delayed memory episode at N_Obj = 2,3,4,6 obj under variety
# of epsilon and N_Quanta... 

include("MDPModelFunctions2.jl")

sim_cowan_att (generic function with 1 method)

In [30]:
N_Quanta = 5;
epsilon = .5
State_Hist_1_Shape = sim_cowan_1_shape(N_Quanta, epsilon; mem_slopes = [.05, .1], N_Trials = 1000, max_NT_per_sec = 800, return_full_hist = false)


2_Objects3_Objects4_Objects6_Objects

Dict{Any, Any} with 6 entries:
  "6_Objects"  => [0.520365 0.53921; 0.52124 0.540644; … ; 0.520461 0.536396; 0…
  "4_Objects"  => [0.52919 0.555467; 0.529318 0.555594; … ; 0.527539 0.548987; …
  "N_Trials"   => 1000
  "mem_slopes" => [0.05, 0.1]
  "3_Objects"  => [0.538683 0.57284; 0.539022 0.573447; … ; 0.534839 0.561971; …
  "2_Objects"  => [0.559067 0.608986; 0.559664 0.610238; … ; 0.558286 0.603679;…

In [49]:
N_Quanta = 50;
epsilon = 0
State_Hist_Att = sim_cowan_att(N_Quanta, epsilon; N_Trials = 1000, max_NT_per_sec = 800, return_full_hist = false, mem_slopes = [.05, .1, .2])


CueR_1.0_N_Obj_Per_Shape_2 CueR_1.0_N_Obj_Per_Shape_3 CueR_0.8_N_Obj_Per_Shape_2 CueR_0.8_N_Obj_Per_Shape_3 CueR_0.5_N_Obj_Per_Shape_2 CueR_0.5_N_Obj_Per_Shape_3 

Dict{Any, Any} with 6 entries:
  "CueR_0.5_N_Obj_Per_Shape_2" => [0.703482 0.698929; 0.705233 0.701969; … ; 0.…
  "CueR_0.8_N_Obj_Per_Shape_2" => [0.696055 0.709826; 0.702971 0.707422; … ; 0.…
  "CueR_0.5_N_Obj_Per_Shape_3" => [0.656254 0.649194; 0.657687 0.650815; … ; 0.…
  "CueR_1.0_N_Obj_Per_Shape_2" => [0.703562 0.704696; 0.709906 0.702284; … ; 0.…
  "CueR_1.0_N_Obj_Per_Shape_3" => [0.653804 0.648297; 0.658225 0.646436; … ; 0.…
  "CueR_0.8_N_Obj_Per_Shape_3" => [0.650942 0.65586; 0.656009 0.653282; … ; 0.7…

In [51]:
State_Hist_Att["CueR_0.8_N_Obj_Per_Shape_2"]

1600×2×3 Array{Float64, 3}:
[:, :, 1] =
 0.696055  0.709826
 0.702971  0.707422
 0.708819  0.704864
 0.714231  0.702746
 0.71919   0.700371
 0.723854  0.697936
 0.728259  0.69566
 0.732042  0.693242
 0.7359    0.691148
 0.739447  0.688877
 0.742888  0.687091
 0.745908  0.685196
 0.748576  0.683451
 ⋮         
 0.804997  0.620016
 0.805156  0.620081
 0.804966  0.620412
 0.805025  0.620383
 0.8049    0.620288
 0.804961  0.620231
 0.804932  0.619864
 0.804821  0.619951
 0.804836  0.619862
 0.804926  0.619723
 0.804992  0.619771
 0.80478   0.619905

[:, :, 2] =
 0.785851  0.803982
 0.797713  0.801753
 0.80727   0.799256
 0.815839  0.797319
 0.823429  0.795086
 0.830273  0.792552
 0.836512  0.790252
 0.841797  0.787809
 0.847037  0.785796
 0.851598  0.783491
 0.855903  0.781826
 0.859642  0.780053
 0.862901  0.778374
 ⋮         
 0.917594  0.708756
 0.917719  0.708844
 0.917575  0.709336
 0.917616  0.709322
 0.917525  0.709151
 0.917568  0.70909
 0.917551  0.708506
 0.917469  0.708626
 0.91

In [17]:
p_rem = State_Hist_1_Shape["6_Objects"]
p_rem

1600×2 Matrix{Float64}:
 0.520844  0.540038
 0.520646  0.539512
 0.520811  0.539696
 0.520326  0.538707
 0.519845  0.537742
 0.520134  0.538169
 0.519721  0.537327
 0.519785  0.537352
 0.519496  0.536756
 0.519665  0.537081
 0.519836  0.537329
 0.519753  0.537152
 0.519972  0.537495
 ⋮         
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002

Cowan 1 shape tests

In [31]:

### Simualte cowan 1 - shape

function sim_cowan_1_shape_return_hist(N_Quanta, epsilon; N_trials = 1000, max_NT_per_sec = 800)

    State_Hist_1_Shape = Dict()

    State_Hist_1_Shape["N_Trials"] = N_Trials

    N_Sec = 2 # check whether this is correct
    # max_NT_per_sec = 1000

    N_Obj_Conds = [2,3,4,6]

    N_n_obj_conds = length(N_Obj_Conds)

    for obj_cond = 1:N_n_obj_conds

        N_Objects = N_Obj_Conds[obj_cond]

        cond_name = "$(N_Objects)_Objects"
        print(cond_name)

        sim_episode_fun = simulate_delayed_memory_episode;

        N_TimeSteps_Pre = max_NT_per_sec*N_Sec
        N_TimeSteps_Post = 0

        # returns N_Timepoints X 
        State_Hist_1_Shape[cond_name] = simulate_task_return_state_hist(N_Quanta, N_Objects, epsilon, N_TimeSteps_Pre, N_TimeSteps_Post, N_Trials, sim_episode_fun; mem_slope = .1);
    end
    return State_Hist_1_Shape
end


N_Quanta = 5
epsilon = .5

sim_cowan_1_shape_return_hist(N_Quanta, epsilon)

2_Objects3_Objects4_Objects6_Objects

Dict{Any, Any} with 5 entries:
  "6_Objects" => [2.0 1.0 … 1.0 1.0; 2.0 1.0 … 0.0 2.0; … ; 0.0 5.0 … 0.0 0.0; …
  "4_Objects" => [1.0 2.0 1.0 1.0; 1.0 1.0 2.0 1.0; … ; 0.0 0.0 0.0 5.0; 0.0 0.…
  "N_Trials"  => 1000
  "3_Objects" => [2.0 0.0 3.0; 3.0 0.0 2.0; … ; 0.0 0.0 5.0; 0.0 0.0 5.0;;; 2.0…
  "2_Objects" => [1.0 4.0; 1.0 4.0; … ; 5.0 0.0; 5.0 0.0;;; 5.0 0.0; 5.0 0.0; ……

In [ ]:
## Now do the multiple shape stuff

# 100%, 80/20, 50% X 4 item or 6 item (with probe probs being enhanced for some of them)

# so 3 attention X 2 attention conds to simualte

# 100%, 80% 50% X 4 item or 6 item (with probe probs being enhanced for some of them)


In [27]:
size(State_Hist_1_Shape[cond_name])

(2000, 6, 1000)

In [89]:
function simulate_precue_episode_cowan(N_Quanta, N_Objects_Total, epsilon, N_TimeSteps_Pre, N_TimeSteps_Post; cue_reliability = 1)
    
    
    # N_Objects_Total = 2*N_Objects_Per_Shape
    N_Objects = N_Objects_Total
    
    N_Objects_Per_Shape = Int(N_Objects_Total/2)
    
    object_probe_probs = zeros(N_Objects_Total)
    object_probe_probs[1:N_Objects_Per_Shape] .= cue_reliability/N_Objects_Per_Shape
    
    object_probe_probs[N_Objects_Per_Shape+1:end] .= (1 - cue_reliability)/N_Objects_Per_Shape
    
   # print(object_probe_probs)
   # print(N_B)
    
    # specify reward distr
    exp_num_time_steps = 10
    per_timestep_probe_prob = 1/exp_num_time_steps
    
    state_history, action_history = simulate_episode(N_Quanta, N_Objects, epsilon, N_TimeSteps_Post, object_probe_probs; s=0)
    
    return state_history
    
end




simulate_precue_episode_cowan (generic function with 1 method)

In [96]:
# This can take 20-30 seconds...
function sim_cowan_att_return_hist(N_Quanta, epsilon; N_trials = 1000, max_NT_per_sec = 800)

    # These are all post cue - though sometimes the cue is uninformative... (then this should basically reduce to the one-shape case)
    
    N_Sec = 2
    N_TimeSteps_Pre = 0
    N_TimeSteps_Post = max_NT_per_sec*N_Sec
    
    CueR_Conds = [1., .8, .5]
    N_CueR_Conds = length(CueR_Conds)

    N_Obj_Per_Shape_Conds = [2, 3]
    N_N_Obj_Per_Shape_Conds = length(N_Obj_Per_Shape_Conds)

    State_Hist_Att = Dict()

    for Cuer_Cond_Idx = 1:N_CueR_Conds
        for N_Obj_Per_Shape_Cond_Idx = 1:N_N_Obj_Per_Shape_Conds

    # Cuer_Cond_Idx=1
    # N_Obj_Per_Shape_Cond_Idx=2
            CueR = CueR_Conds[Cuer_Cond_Idx]
            N_Obj_Per_Shape = N_Obj_Per_Shape_Conds[N_Obj_Per_Shape_Cond_Idx]

            N_Objects_Total = 2*N_Obj_Per_Shape;

            cond_name = "CueR_$(CueR)_N_Obj_Per_Shape_$(N_Obj_Per_Shape)"
            print(string(cond_name, " "))

            sim_episode_fun = simulate_precue_episode_cowan;



            State_Hist_Att[cond_name] = simulate_task_return_state_hist(N_Quanta, N_Objects_Total, epsilon, N_TimeSteps_Pre, N_TimeSteps_Post, N_Trials, sim_episode_fun; cue_reliability = CueR);
        end
    end
    return State_Hist_Att
end

N_Quanta = 5
epsilon = .5

State_Hist_Att = sim_cowan_att_return_hist(N_Quanta, epsilon)

CueR_1.0_N_Obj_Per_Shape_2 CueR_1.0_N_Obj_Per_Shape_3 CueR_0.8_N_Obj_Per_Shape_2 CueR_0.8_N_Obj_Per_Shape_3 CueR_0.5_N_Obj_Per_Shape_2 CueR_0.5_N_Obj_Per_Shape_3 

Dict{Any, Any} with 6 entries:
  "CueR_0.5_N_Obj_Per_Shape_2" => [1.0 2.0 1.0 1.0; 1.0 3.0 0.0 1.0; … ; 0.0 0.…
  "CueR_0.8_N_Obj_Per_Shape_2" => [1.0 2.0 0.0 2.0; 2.0 2.0 0.0 1.0; … ; 5.0 0.…
  "CueR_0.5_N_Obj_Per_Shape_3" => [1.0 1.0 … 0.0 2.0; 0.0 1.0 … 0.0 3.0; … ; 0.…
  "CueR_1.0_N_Obj_Per_Shape_2" => [1.0 2.0 0.0 2.0; 1.0 2.0 0.0 2.0; … ; 0.0 5.…
  "CueR_1.0_N_Obj_Per_Shape_3" => [0.0 2.0 … 1.0 1.0; 0.0 2.0 … 1.0 1.0; … ; 0.…
  "CueR_0.8_N_Obj_Per_Shape_3" => [1.0 0.0 … 0.0 0.0; 1.0 0.0 … 0.0 0.0; … ; 0.…

In [93]:
State_Hist_Att

Dict{Any, Any} with 6 entries:
  "CueR_0.5_N_Obj_Per_Shape_2" => [1.0 1.0 2.0 1.0; 0.0 2.0 2.0 1.0; … ; 0.0 0.…
  "CueR_0.8_N_Obj_Per_Shape_2" => [1.0 2.0 1.0 1.0; 1.0 2.0 1.0 1.0; … ; 0.0 5.…
  "CueR_0.5_N_Obj_Per_Shape_3" => [0.0 2.0 … 1.0 0.0; 0.0 1.0 … 2.0 0.0; … ; 0.…
  "CueR_1.0_N_Obj_Per_Shape_2" => [2.0 1.0 1.0 1.0; 1.0 2.0 1.0 1.0; … ; 0.0 5.…
  "CueR_1.0_N_Obj_Per_Shape_3" => [0.0 1.0 … 2.0 1.0; 0.0 2.0 … 2.0 0.0; … ; 0.…
  "CueR_0.8_N_Obj_Per_Shape_3" => [1.0 0.0 … 0.0 1.0; 1.0 0.0 … 0.0 1.0; … ; 0.…

In [52]:
simulate_precue_episode_cowan(N_Quanta, N_Objects_Per_Shape, epsilon, N_TimeSteps_Pre, N_TimeSteps_Post; cue_reliability = 1)

0×6 Matrix{Float64}

In [45]:
sum(object_probe_probs)

1.0

In [ ]:
"