### ALL Conditions:

1-shape: (2 3 4 or 6 items) - just delayed forgetting / equal probe probs

Attention conditions - precues with

100%, 80/20, 50% X 4 item or 6 item (with probe probs being enhanced for some of them)

### For all of these, you can just run for a ton of Time-Steps to remove the TS-per-sec parameters -- just get number of time-steps...






In [27]:
# part 1:
# simulate the delayed memory episode at N_Obj = 2,3,4,6 obj under variety
# of epsilon and N_Quanta... 

include("MDPModelFunctions2.jl")

sim_cowan_att (generic function with 1 method)

In [30]:
N_Quanta = 5;
epsilon = .5
State_Hist_1_Shape = sim_cowan_1_shape(N_Quanta, epsilon; mem_slopes = [.05, .1], N_Trials = 1000, max_NT_per_sec = 800, return_full_hist = false)


2_Objects3_Objects4_Objects6_Objects

Dict{Any, Any} with 6 entries:
  "6_Objects"  => [0.520365 0.53921; 0.52124 0.540644; … ; 0.520461 0.536396; 0…
  "4_Objects"  => [0.52919 0.555467; 0.529318 0.555594; … ; 0.527539 0.548987; …
  "N_Trials"   => 1000
  "mem_slopes" => [0.05, 0.1]
  "3_Objects"  => [0.538683 0.57284; 0.539022 0.573447; … ; 0.534839 0.561971; …
  "2_Objects"  => [0.559067 0.608986; 0.559664 0.610238; … ; 0.558286 0.603679;…

In [ ]:
N_Quanta = 50;
epsilon = 0
State_Hist_Att = sim_cowan_att(N_Quanta, epsilon; N_Trials = 1000, max_NT_per_sec = 800, return_full_hist = false, mem_slopes = [.05, .1, .2])


CueR_1.0_N_Obj_Per_Shape_2 CueR_1.0_N_Obj_Per_Shape_3 CueR_0.8_N_Obj_Per_Shape_2 CueR_0.8_N_Obj_Per_Shape_3 

In [48]:
State_Hist_Att["CueR_1.0_N_Obj_Per_Shape_2"]

1600×2×3 Array{Float64, 3}:
[:, :, 1] =
 0.5295    0.53011
 0.534866  0.524768
 0.539323  0.519982
 0.542535  0.516555
 0.545232  0.514144
 0.547354  0.511927
 0.548646  0.510382
 0.550391  0.508924
 0.551563  0.507519
 0.552591  0.506382
 0.55325   0.505807
 0.553659  0.505144
 0.554475  0.504345
 ⋮         
 0.556093  0.502101
 0.556115  0.502101
 0.555872  0.502101
 0.555673  0.502101
 0.555784  0.502101
 0.556115  0.502101
 0.555872  0.502101
 0.556026  0.502101
 0.555651  0.502101
 0.5566    0.502101
 0.555497  0.502101
 0.556071  0.502101

[:, :, 2] =
 0.556144  0.557205
 0.565993  0.547298
 0.57387   0.538344
 0.579496  0.531854
 0.58416   0.527247
 0.587808  0.522972
 0.590004  0.519946
 0.592984  0.517111
 0.594953  0.514387
 0.596647  0.512185
 0.597773  0.511039
 0.598442  0.50974
 0.599848  0.508194
 ⋮         
 0.602543  0.503738
 0.602582  0.503738
 0.602153  0.503738
 0.601803  0.503738
 0.601997  0.503738
 0.602582  0.503738
 0.602153  0.503738
 0.602426  0.503738
 0.60

In [17]:
p_rem = State_Hist_1_Shape["6_Objects"]
p_rem

1600×2 Matrix{Float64}:
 0.520844  0.540038
 0.520646  0.539512
 0.520811  0.539696
 0.520326  0.538707
 0.519845  0.537742
 0.520134  0.538169
 0.519721  0.537327
 0.519785  0.537352
 0.519496  0.536756
 0.519665  0.537081
 0.519836  0.537329
 0.519753  0.537152
 0.519972  0.537495
 ⋮         
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002
 0.52024   0.536002

Cowan 1 shape tests

In [31]:

### Simualte cowan 1 - shape

function sim_cowan_1_shape_return_hist(N_Quanta, epsilon; N_trials = 1000, max_NT_per_sec = 800)

    State_Hist_1_Shape = Dict()

    State_Hist_1_Shape["N_Trials"] = N_Trials

    N_Sec = 2 # check whether this is correct
    # max_NT_per_sec = 1000

    N_Obj_Conds = [2,3,4,6]

    N_n_obj_conds = length(N_Obj_Conds)

    for obj_cond = 1:N_n_obj_conds

        N_Objects = N_Obj_Conds[obj_cond]

        cond_name = "$(N_Objects)_Objects"
        print(cond_name)

        sim_episode_fun = simulate_delayed_memory_episode;

        N_TimeSteps_Pre = max_NT_per_sec*N_Sec
        N_TimeSteps_Post = 0

        # returns N_Timepoints X 
        State_Hist_1_Shape[cond_name] = simulate_task_return_state_hist(N_Quanta, N_Objects, epsilon, N_TimeSteps_Pre, N_TimeSteps_Post, N_Trials, sim_episode_fun; mem_slope = .1);
    end
    return State_Hist_1_Shape
end


N_Quanta = 5
epsilon = .5

sim_cowan_1_shape_return_hist(N_Quanta, epsilon)

2_Objects3_Objects4_Objects6_Objects

Dict{Any, Any} with 5 entries:
  "6_Objects" => [2.0 1.0 … 1.0 1.0; 2.0 1.0 … 0.0 2.0; … ; 0.0 5.0 … 0.0 0.0; …
  "4_Objects" => [1.0 2.0 1.0 1.0; 1.0 1.0 2.0 1.0; … ; 0.0 0.0 0.0 5.0; 0.0 0.…
  "N_Trials"  => 1000
  "3_Objects" => [2.0 0.0 3.0; 3.0 0.0 2.0; … ; 0.0 0.0 5.0; 0.0 0.0 5.0;;; 2.0…
  "2_Objects" => [1.0 4.0; 1.0 4.0; … ; 5.0 0.0; 5.0 0.0;;; 5.0 0.0; 5.0 0.0; ……

In [ ]:
## Now do the multiple shape stuff

# 100%, 80/20, 50% X 4 item or 6 item (with probe probs being enhanced for some of them)

# so 3 attention X 2 attention conds to simualte

# 100%, 80% 50% X 4 item or 6 item (with probe probs being enhanced for some of them)


In [27]:
size(State_Hist_1_Shape[cond_name])

(2000, 6, 1000)

In [89]:
function simulate_precue_episode_cowan(N_Quanta, N_Objects_Total, epsilon, N_TimeSteps_Pre, N_TimeSteps_Post; cue_reliability = 1)
    
    
    # N_Objects_Total = 2*N_Objects_Per_Shape
    N_Objects = N_Objects_Total
    
    N_Objects_Per_Shape = Int(N_Objects_Total/2)
    
    object_probe_probs = zeros(N_Objects_Total)
    object_probe_probs[1:N_Objects_Per_Shape] .= cue_reliability/N_Objects_Per_Shape
    
    object_probe_probs[N_Objects_Per_Shape+1:end] .= (1 - cue_reliability)/N_Objects_Per_Shape
    
   # print(object_probe_probs)
   # print(N_B)
    
    # specify reward distr
    exp_num_time_steps = 10
    per_timestep_probe_prob = 1/exp_num_time_steps
    
    state_history, action_history = simulate_episode(N_Quanta, N_Objects, epsilon, N_TimeSteps_Post, object_probe_probs; s=0)
    
    return state_history
    
end




simulate_precue_episode_cowan (generic function with 1 method)

In [96]:
# This can take 20-30 seconds...
function sim_cowan_att_return_hist(N_Quanta, epsilon; N_trials = 1000, max_NT_per_sec = 800)

    # These are all post cue - though sometimes the cue is uninformative... (then this should basically reduce to the one-shape case)
    
    N_Sec = 2
    N_TimeSteps_Pre = 0
    N_TimeSteps_Post = max_NT_per_sec*N_Sec
    
    CueR_Conds = [1., .8, .5]
    N_CueR_Conds = length(CueR_Conds)

    N_Obj_Per_Shape_Conds = [2, 3]
    N_N_Obj_Per_Shape_Conds = length(N_Obj_Per_Shape_Conds)

    State_Hist_Att = Dict()

    for Cuer_Cond_Idx = 1:N_CueR_Conds
        for N_Obj_Per_Shape_Cond_Idx = 1:N_N_Obj_Per_Shape_Conds

    # Cuer_Cond_Idx=1
    # N_Obj_Per_Shape_Cond_Idx=2
            CueR = CueR_Conds[Cuer_Cond_Idx]
            N_Obj_Per_Shape = N_Obj_Per_Shape_Conds[N_Obj_Per_Shape_Cond_Idx]

            N_Objects_Total = 2*N_Obj_Per_Shape;

            cond_name = "CueR_$(CueR)_N_Obj_Per_Shape_$(N_Obj_Per_Shape)"
            print(string(cond_name, " "))

            sim_episode_fun = simulate_precue_episode_cowan;



            State_Hist_Att[cond_name] = simulate_task_return_state_hist(N_Quanta, N_Objects_Total, epsilon, N_TimeSteps_Pre, N_TimeSteps_Post, N_Trials, sim_episode_fun; cue_reliability = CueR);
        end
    end
    return State_Hist_Att
end

N_Quanta = 5
epsilon = .5

State_Hist_Att = sim_cowan_att_return_hist(N_Quanta, epsilon)

CueR_1.0_N_Obj_Per_Shape_2 CueR_1.0_N_Obj_Per_Shape_3 CueR_0.8_N_Obj_Per_Shape_2 CueR_0.8_N_Obj_Per_Shape_3 CueR_0.5_N_Obj_Per_Shape_2 CueR_0.5_N_Obj_Per_Shape_3 

Dict{Any, Any} with 6 entries:
  "CueR_0.5_N_Obj_Per_Shape_2" => [1.0 2.0 1.0 1.0; 1.0 3.0 0.0 1.0; … ; 0.0 0.…
  "CueR_0.8_N_Obj_Per_Shape_2" => [1.0 2.0 0.0 2.0; 2.0 2.0 0.0 1.0; … ; 5.0 0.…
  "CueR_0.5_N_Obj_Per_Shape_3" => [1.0 1.0 … 0.0 2.0; 0.0 1.0 … 0.0 3.0; … ; 0.…
  "CueR_1.0_N_Obj_Per_Shape_2" => [1.0 2.0 0.0 2.0; 1.0 2.0 0.0 2.0; … ; 0.0 5.…
  "CueR_1.0_N_Obj_Per_Shape_3" => [0.0 2.0 … 1.0 1.0; 0.0 2.0 … 1.0 1.0; … ; 0.…
  "CueR_0.8_N_Obj_Per_Shape_3" => [1.0 0.0 … 0.0 0.0; 1.0 0.0 … 0.0 0.0; … ; 0.…

In [93]:
State_Hist_Att

Dict{Any, Any} with 6 entries:
  "CueR_0.5_N_Obj_Per_Shape_2" => [1.0 1.0 2.0 1.0; 0.0 2.0 2.0 1.0; … ; 0.0 0.…
  "CueR_0.8_N_Obj_Per_Shape_2" => [1.0 2.0 1.0 1.0; 1.0 2.0 1.0 1.0; … ; 0.0 5.…
  "CueR_0.5_N_Obj_Per_Shape_3" => [0.0 2.0 … 1.0 0.0; 0.0 1.0 … 2.0 0.0; … ; 0.…
  "CueR_1.0_N_Obj_Per_Shape_2" => [2.0 1.0 1.0 1.0; 1.0 2.0 1.0 1.0; … ; 0.0 5.…
  "CueR_1.0_N_Obj_Per_Shape_3" => [0.0 1.0 … 2.0 1.0; 0.0 2.0 … 2.0 0.0; … ; 0.…
  "CueR_0.8_N_Obj_Per_Shape_3" => [1.0 0.0 … 0.0 1.0; 1.0 0.0 … 0.0 1.0; … ; 0.…

In [52]:
simulate_precue_episode_cowan(N_Quanta, N_Objects_Per_Shape, epsilon, N_TimeSteps_Pre, N_TimeSteps_Post; cue_reliability = 1)

0×6 Matrix{Float64}

In [45]:
sum(object_probe_probs)

1.0

In [ ]:
"