In [15]:
include("MDPModelFunctions2.jl")
using JLD2
using PythonPlot

    CondaPkg Found dependencies: /Users/erussek/.julia/packages/PythonCall/wXfah/CondaPkg.toml
    CondaPkg Found dependencies: /Users/erussek/.julia/packages/PythonPlot/KcWMF/CondaPkg.toml
    CondaPkg Dependencies already up to date


In [57]:
to_save_folder = "/Users/erussek/Dropbox/Griffiths_Lab_Stuff/code/Memory_Models/shimi_bbopts"

# re-run with new values so we can see some concavity...
NT_vals = collect(100:250:2200)
N_nt = length(NT_vals)
mem_slopes = round.([.01*(1.5^x) for x = 2:9], digits = 3)
N_ms = length(mem_slopes)

# get child res...

child_vals = zeros(N_nt, N_ms)


adult_vals = zeros(N_nt, N_ms)
adult_epsilon = zeros(N_nt, N_ms)
adult_quanta = zeros(N_nt, N_ms)
child_epsilon = zeros(N_nt, N_ms)
child_quanta = zeros(N_nt, N_ms)

for (ms_idx,ms) in enumerate(mem_slopes)
    for (nt_idx,nt) in enumerate(NT_vals)
        which_group = "child"

        try
            file_name = "Group_$(which_group)_NT_$(nt)_memslope_$(ms).jld2"
            full_file_path = joinpath(to_save_folder,file_name)
            res = load(full_file_path)
            child_vals[nt_idx, ms_idx] = res["res_dict"]["val"]
            
            child_quanta[nt_idx,ms_idx] = res["res_dict"]["x"][1]
            child_epsilon[nt_idx,ms_idx] = res["res_dict"]["x"][2]
        catch
            print("$(ms), $(nt)")
            child_vals[nt_idx, ms_idx] = 0

        end
        which_group = "adult"
        try
            file_name = "Group_$(which_group)_NT_$(nt)_memslope_$(ms).jld2"
            full_file_path = joinpath(to_save_folder,file_name)
            res = load(full_file_path)
            adult_vals[nt_idx, ms_idx] = res["res_dict"]["val"]
            adult_quanta[nt_idx,ms_idx] = res["res_dict"]["x"][1]
            adult_epsilon[nt_idx,ms_idx] = res["res_dict"]["x"][2]
        catch
            print("$(ms), $(nt)")
            adult_vals[nt_idx, ms_idx] = NaN
        end
    end
end
        


0.034, 1100

In [62]:
mem_slopes

8-element Vector{Float64}:
 0.022
 0.034
 0.051
 0.076
 0.114
 0.171
 0.256
 0.384

In [66]:
NT_vals

9-element Vector{Int64}:
  100
  350
  600
  850
 1100
 1350
 1600
 1850
 2100

In [71]:
adult_vals

9×8 Matrix{Float64}:
 10.6886   2.69477  2.49831  2.37629  2.22494  1.63828  1.32259  1.22152
  9.02076  3.57391  2.45553  2.40433  1.6505   1.15433  1.36281  1.61833
  9.94535  3.4622   2.57021  2.03097  2.93847  1.55256  1.3521   3.00754
  9.79437  3.35798  3.91752  1.60006  2.705    1.09384  1.34083  1.38933
 11.237    5.03286  2.57532  3.23824  1.31739  1.44451  1.27363  2.20969
 10.2161   3.24491  2.16472  4.18664  1.24075  1.79336  1.4396   1.71658
 10.2866   7.33877  1.85136  3.24638  2.09615  3.10679  1.7882   1.94671
 10.2682   6.48901  6.36214  4.10271  2.02981  1.86849  2.91864  2.02029
 10.3449   5.10431  2.5051   1.15026  4.93666  1.84152  1.64753  4.65314

In [44]:
adult_quanta

9×8 Matrix{Float64}:
 0.998454  0.993996  0.717982  0.496096  …  0.218641  0.145648  0.111803
 0.996724  0.909047  0.786689  0.593852     0.247853  0.167576  0.123883
 0.998746  0.96844   0.752359  0.530903     0.233094  0.144988  0.137582
 0.988119  0.960811  0.731252  0.568889     0.261723  0.159009  0.115174
 0.938479  0.816338  0.726644  0.445162     0.223074  0.164151  0.127401
 0.976197  0.982396  0.746841  0.424758  …  0.198002  0.156178  0.128359
 0.973692  0.943943  0.880872  0.559466     0.318989  0.173535  0.136454
 0.990612  0.821311  0.823859  0.359659     0.344348  0.215646  0.126141
 0.990466  0.913589  0.748965  0.561724     0.354451  0.155473  0.123885

In [61]:
adult_epsilon

9×8 Matrix{Float64}:
 0.00930702  0.206081  0.473488  0.656413  …  0.716735  0.611474  0.30855
 0.321144    0.723689  0.872449  0.895807     0.808455  0.558972  0.37043
 0.325852    0.812165  0.895903  0.892175     0.7098    0.289188  0.289663
 0.616153    0.902859  0.86934   0.936561     0.801794  0.442696  0.215971
 0.503263    0.917058  0.928016  0.86255      0.684169  0.490929  0.195975
 0.476078    0.939189  0.950587  0.82899   …  0.617766  0.468052  0.32857
 0.771466    0.466126  0.957959  0.903903     0.793727  0.396404  0.403702
 0.0780956   0.859437  0.902703  0.820204     0.878511  0.586155  0.30345
 0.467385    0.900097  0.937401  0.931105     0.862144  0.427555  0.335325

In [45]:
child_quanta

9×8 Matrix{Float64}:
 0.514451  0.329476  0.222066  0.135796  …  0.0751348  0.0493959  0.0257428
 0.496902  0.329122  0.219812  0.113281     0.0858834  0.102846   0.0310303
 0.639005  0.189589  0.153245  0.13576      0.0691097  0.0696297  0.0445889
 0.665231  0.271714  0.308419  0.202466     0.266534   0.0837416  0.0958387
 0.479795  0.0       0.211432  0.174645     0.119025   0.0469214  0.113179
 0.730845  0.392285  0.354361  0.170625  …  0.0928727  0.0582865  0.166821
 0.823476  0.256072  0.237456  0.118933     0.332247   0.108845   0.0296026
 0.268784  0.274826  0.233788  0.122667     0.105854   0.12607    0.0385879
 0.273475  0.389722  0.194242  0.108001     0.139464   0.11653    0.146761

In [46]:
adult_epsilon

9×8 Matrix{Float64}:
 0.00930702  0.206081  0.473488  0.656413  …  0.716735  0.611474  0.30855
 0.321144    0.723689  0.872449  0.895807     0.808455  0.558972  0.37043
 0.325852    0.812165  0.895903  0.892175     0.7098    0.289188  0.289663
 0.616153    0.902859  0.86934   0.936561     0.801794  0.442696  0.215971
 0.503263    0.917058  0.928016  0.86255      0.684169  0.490929  0.195975
 0.476078    0.939189  0.950587  0.82899   …  0.617766  0.468052  0.32857
 0.771466    0.466126  0.957959  0.903903     0.793727  0.396404  0.403702
 0.0780956   0.859437  0.902703  0.820204     0.878511  0.586155  0.30345
 0.467385    0.900097  0.937401  0.931105     0.862144  0.427555  0.335325

In [47]:
child_epsilon

9×8 Matrix{Float64}:
 0.774844  0.8399    0.848047  0.852733  …  0.808281  0.662803  0.393113
 0.92954   0.925604  0.910196  0.685528     0.81741   0.886225  0.229791
 0.949276  0.518445  0.802126  0.870452     0.603328  0.670564  0.298676
 0.986599  0.894089  0.973505  0.934775     0.97336   0.724534  0.840138
 0.944257  0.0       0.888285  0.866054     0.843967  0.565629  0.902343
 0.984035  0.972668  0.969544  0.895239  …  0.780778  0.622741  0.916661
 0.989667  0.895289  0.9565    0.790925     0.982704  0.817192  0.0987156
 0.666735  0.898718  0.924567  0.48182      0.808819  0.872039  0.229067
 0.875562  0.98506   0.754306  0.81925      0.862944  0.762413  0.923948

In [51]:
adult_vals

9×8 Matrix{Float64}:
 10.6886   2.69477  2.49831  2.37629  2.22494  1.63828  1.32259  1.22152
  9.02076  3.57391  2.45553  2.40433  1.6505   1.15433  1.36281  1.61833
  9.94535  3.4622   2.57021  2.03097  2.93847  1.55256  1.3521   3.00754
  9.79437  3.35798  3.91752  1.60006  2.705    1.09384  1.34083  1.38933
 11.237    5.03286  2.57532  3.23824  1.31739  1.44451  1.27363  2.20969
 10.2161   3.24491  2.16472  4.18664  1.24075  1.79336  1.4396   1.71658
 10.2866   7.33877  1.85136  3.24638  2.09615  3.10679  1.7882   1.94671
 10.2682   6.48901  6.36214  4.10271  2.02981  1.86849  2.91864  2.02029
 10.3449   5.10431  2.5051   1.15026  4.93666  1.84152  1.64753  4.65314

In [27]:
fig,ax = subplots(1,figsize=(2,2),dpi=200)
ax.imshow(mem_slopes, NT_vals,child_vals)


LoadError: Python: TypeError: 'norm' must be an instance of matplotlib.colors.Normalize, str or None, not a juliacall.ArrayValue

In [ ]:
to_save_folder = "/Users/erussek/Dropbox/Griffiths_Lab_Stuff/code/Memory_Models/shimi_bbopts"


In [36]:
res["res_dict"]["x"]

2-element Vector{Float64}:
 0.12388473783069451
 0.3353248144890226

In [6]:
ms = mem_slopes[1]
nt = NT_vals[1]

file_name = "Group_$(which_group)_NT_$(nt)_memslope_$(ms).jld2"
full_file_path = joinpath(to_save_folder,file_name)
res = load(full_file_path)

Dict{String, Any} with 1 entry:
  "res_dict" => Dict{Any, Any}("nt"=>100, "val"=>1.28552, "ms"=>0.022, "x"=>[0.…